project_id = "mggxvtfgakplzzpcclte"

[functions.widget]
verify_jwt = false

[functions.generate-outfits]
verify_jwt = true

[functions.virtual-tryon]
verify_jwt = true

[functions.styling-chat]
verify_jwt = false

[functions.shopify-oauth]
verify_jwt = false

[functions.shopify-proxy]
verify_jwt = false

[functions.shopify-app-proxy]
verify_jwt = false

[functions.shopify-webhooks]
verify_jwt = false

[functions.shopify-product-sync]
verify_jwt = true

[functions.account-bootstrap]
verify_jwt = false

[functions.woocommerce-product-sync]
verify_jwt = true

[functions.widget-loader]
verify_jwt = false

[functions.shopify-widget-toggle]
verify_jwt = false
